### ISSUE TITLE
npm run dev:mp-dev 编译报错  

### ISSUE THREAD

**Issue by paulloo** [lexmin0412/taro3-react-template#2]
![image](https://user-images.githubusercontent.com/32083925/154021166-7452b4df-44d4-4b6e-9fc6-7d2f5ce64812.png)

**Comment by paulloo** [comment]
https://github.com/NervJS/taro/issues/9605

https://github.com/NervJS/taro/issues/9398

这两个好使

**Comment by lexmin0412** [comment]
> [NervJS/taro#9605](https://github.com/NervJS/taro/issues/9605)
> 
> [NervJS/taro#9398](https://github.com/NervJS/taro/issues/9398)
> 
> 这两个好使

所以是换成yarn重装依赖就没问题了哈
