### ISSUE TITLE
请问缩进为4个空格是专门设置过吗？我想设置缩进2个空格该在哪里设置？

### ISSUE THREAD

**Issue by 358xiaoyihezemin** [lexmin0412/taro3-react-template#4]
如题

**Comment by lexmin0412** [comment]
如果你vscode装了prettier插件的话，我在.prettierrc.js里面继承了@youtils/prettier-config-standard配置，里面使用的是tab: 2的缩进风格，如果缩进表现为space:4 的话，可以检查下vscode是否有配置单独的缩进。
