### ISSUE TITLE
插件依赖 "taro-plugin-dotenv" 加载失败，请检查插件配置

### ISSUE THREAD

**Issue by zhengwenf199000** [lexmin0412/taro3-react-template#5]
### Describe the bug

运行不起来啊 咋回事，报 插件依赖 "taro-plugin-dotenv" 加载失败，请检查插件配置

### Reproduction

试了用npm pnpm yarn都不行

### System Info

```Shell
试了用npm pnpm yarn都不行
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by lexmin0412** [comment]
### 问题原因：
- taro-plugin-dotenv 插件内部读取了根目录下的 .env 文件作为环境变量写入
- taro 对插件的异常处理有点粗暴了，插件内部逻辑报错它就会抛出主楼的错误

### 解决方案：
在项目根目录下创建 .env 文件，写入如下内容即可：
```env
TARO_API_BASE=/api
```

**Comment by lexmin0412** [comment]
@zhengwenf199000 更新了一下taro-plugin-dotenv 的版本，现在不加 .env 也不会启动失败了，不过代码中有些用到 process.env 的地方，可以注释掉。
