### ISSUE TITLE
期望作者能够 增加 目录结构的解释 能否给出代码中form校验的类的展示

### ISSUE THREAD

**Issue by ziu96** [lexmin0412/taro3-react-template#7]
### Clear and concise description of the problem

期望作者能够 增加 目录结构的解释 能否给出代码中form校验的类的展示

### Suggested solution

增加目录结构的解释  辛苦作者了

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by lexmin0412** [comment]
1. 目录

**Comment by ziu96** [comment]
> @ziu96
> 
> 1. 目录结构已经在 README 补充，[点我](https://github.com/lexmin0412/taro3-react-template#%E7%9B%AE%E5%BD%95%E7%BB%93%E6%9E%84) 查看
> 2. 代码中 form 校验的类的展示，没有理解你的需求是什么，可以补充一下描述
> 3. 上班时间 issue 回复不是很及时，还有其他问题可以加我微信方便沟通 worldpeace20220716

就是 我有看到 大佬你封装了一个form 校验的类 我想知道有没有示例用法 已经satr 谢谢大佬 这个框架对我帮助很大

**Comment by ziu96** [comment]
> @ziu96
> 
> 1. 目录结构已经在 README 补充，[点我](https://github.com/lexmin0412/taro3-react-template#%E7%9B%AE%E5%BD%95%E7%BB%93%E6%9E%84) 查看
> 2. 代码中 form 校验的类的展示，没有理解你的需求是什么，可以补充一下描述
> 3. 上班时间 issue 回复不是很及时，还有其他问题可以加我微信方便沟通 worldpeace20220716

@lexmin0412  谢谢大佬 我的意思是 我有看到大佬你封装了 一个 validator的校验类 想知道是怎么用的 https://github.com/lexmin0412/taro3-react-template/blob/main/src/shared/utils/validator.ts

**Comment by lexmin0412** [comment]
@ziu96 其实这个不用深究了，只是自己做了一点小封装，就是一个类似于 async-validator 的实现。

如果确实想看效果的话，我写了一个小demo，代码在 [这里](https://github.com/lexmin0412/taro3-react-template/blob/main/src/demo/form/form.tsx) 。

更新代码后启动项目，通过 http://localhost:9001/demo/form/form 访问即可，效果如下：

<img width="393" alt="image" src="https://user-images.githubusercontent.com/24385370/234654294-6bf92206-2e70-4053-b49b-7b96d0447411.png">

**Comment by ziu96** [comment]
@lexmin0412 谢谢大佬
