### ISSUE TITLE
为什么没有选择使用最新的nutui-react-taro:2.4呢？

### ISSUE THREAD

**Issue by wozzup** [lexmin0412/taro3-react-template#9]
### Clear and concise description of the problem

ui层面，为什么没有选择使用最新版的 `nutui-react-taro:2.4` 呢？

### Suggested solution

我修改了 package.json 的 `"@nutui/nutui-react-taro": "^2.4.2"` 也是可以正常编译的呢，未来开发上会有兼容的问题吗？

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by lexmin0412** [comment]
单纯只是我引入的时候 nutui 还没有发布 2.x 版本哈哈，谢谢提醒，我找时间测试一下，确认没问题就更新到最新版本。

**Comment by lexmin0412** [comment]
@wozzup 已升级至 `@nutui/nutui-react-taro` 最新版本 2.5.2([#9a1e11a](https://github.com/lexmin0412/taro3-react-template/commit/9a1e11a9dd7a720f574e94c677d66cbb51a902e3)).
